version: '3'

services:
  postgres:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=template
    networks:
      - template-private-network

  template:
    container_name: template
    hostname: template
    image: template:dev

    build:
      context: .
      dockerfile: .docker/development.dockerfile
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - "3005:3000"
    working_dir: /opt/app
    environment:
      NODE_ENV: dev
    networks:
      - template-private-network
    entrypoint: npm run start:dev
    depends_on:
      - postgres


networks:
  template-private-network:
    driver: bridge
